import { NextResponse } from "next/server";

export async function GET() {
  const backendUrl = process.env.BACKEND_URL || "http://localhost:8000";
  try {
    const res = await fetch(`${backendUrl}/api/v1/radar/stations`, { cache: "no-store" });
    if (res.ok) {
      const data = await res.json();
      return NextResponse.json(data);
    }
  } catch (e) {
    console.error("❌ [API Proxy /api/admin/radar] Backend error:", e);
  }

  // Resilient fallback stations for admin viewer (13 stations)
  return NextResponse.json({
    stations: [
      {
        code: "kkn120",
        name: "Khon Kaen (120km) / ขอนแก่น",
        center_lat: 16.4322,
        center_lng: 102.8236,
        radius_km: 120,
        status: "online",
        latency_minutes: 5.0,
        last_frame_timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/kkn/kkn120_latest.gif",
        loop_url: "https://weather.tmd.go.th/kknLoop.php",
      },
      {
        code: "kkn240",
        name: "Khon Kaen (240km) / ขอนแก่น",
        center_lat: 16.4322,
        center_lng: 102.8236,
        radius_km: 240,
        status: "online",
        latency_minutes: 6.5,
        last_frame_timestamp: new Date(Date.now() - 6.5 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/kkn/kkn240_latest.gif",
        loop_url: "https://weather.tmd.go.th/kknLoop.php",
      },
      {
        code: "skn240",
        name: "Sakon Nakhon (240km) / สกลนคร",
        center_lat: 17.1607,
        center_lng: 104.1486,
        radius_km: 240,
        status: "online",
        latency_minutes: 12.0,
        last_frame_timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/skn/skn240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/sknLoop.php",
      },
      {
        code: "ubn240",
        name: "Ubon Ratchathani (240km) / อุบลราชธานี",
        center_lat: 15.2447,
        center_lng: 104.8711,
        radius_km: 240,
        status: "online",
        latency_minutes: 8.0,
        last_frame_timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/ubn/ubn240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/ubnLoop.php",
      },
      {
        code: "svp240",
        name: "Bangkok Suvarnabhumi (240km) / สุวรรณภูมิ",
        center_lat: 13.686,
        center_lng: 100.7486,
        radius_km: 240,
        status: "online",
        latency_minutes: 4.5,
        last_frame_timestamp: new Date(Date.now() - 4.5 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/svp/svp240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/svpLoop.php",
      },
      {
        code: "chn",
        name: "Chainat (240km) / ชัยนาท",
        center_lat: 15.1582,
        center_lng: 100.1912,
        radius_km: 240,
        status: "online",
        latency_minutes: 9.0,
        last_frame_timestamp: new Date(Date.now() - 9 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/chn/chn240_latest.gif",
        loop_url: "https://weather.tmd.go.th/chn.php",
      },
      {
        code: "ryg",
        name: "Rayong (240km) / ระยอง",
        center_lat: 12.6814,
        center_lng: 101.2817,
        radius_km: 240,
        status: "online",
        latency_minutes: 7.0,
        last_frame_timestamp: new Date(Date.now() - 7 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/ryg/ryg240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/rygloop.php",
      },
      {
        code: "phs",
        name: "Phitsanulok (240km) / พิษณุโลก",
        center_lat: 16.7828,
        center_lng: 100.2786,
        radius_km: 240,
        status: "online",
        latency_minutes: 6.0,
        last_frame_timestamp: new Date(Date.now() - 6 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/phs/phs240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/phsloop.php",
      },
      {
        code: "cmp",
        name: "Chumphon (240km) / ชุมพร",
        center_lat: 10.4931,
        center_lng: 99.18,
        radius_km: 240,
        status: "online",
        latency_minutes: 8.5,
        last_frame_timestamp: new Date(Date.now() - 8.5 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/cmp/cmp240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/cmploop.php",
      },
      {
        code: "tak",
        name: "Doi Muser, Tak Province (240km) / ตาก",
        center_lat: 16.75,
        center_lng: 98.93,
        radius_km: 240,
        status: "online",
        latency_minutes: 11.0,
        last_frame_timestamp: new Date(Date.now() - 11 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/tak/tak240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/takloop.php",
      },
      {
        code: "cri",
        name: "Chiang Rai (240km) / เชียงราย",
        center_lat: 19.9609,
        center_lng: 99.8824,
        radius_km: 240,
        status: "online",
        latency_minutes: 7.5,
        last_frame_timestamp: new Date(Date.now() - 7.5 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/cri/cri240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/criloop.php",
      },
      {
        code: "srt",
        name: "Surat Thani (240km) / สุราษฎร์ธานี",
        center_lat: 9.1333,
        center_lng: 99.3333,
        radius_km: 240,
        status: "online",
        latency_minutes: 9.5,
        last_frame_timestamp: new Date(Date.now() - 9.5 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/srt/srt240_latest.png",
        loop_url: "https://weather.tmd.go.th/srtloop.php",
      },
      {
        code: "hyi",
        name: "Hat Yai (240km) / หาดใหญ่",
        center_lat: 6.9248,
        center_lng: 100.4385,
        radius_km: 240,
        status: "online",
        latency_minutes: 5.5,
        last_frame_timestamp: new Date(Date.now() - 5.5 * 60000).toISOString(),
        image_url: "https://weather.tmd.go.th/hyi/hyi240_latest.jpg",
        loop_url: "https://weather.tmd.go.th/hyiloop.php",
      },
    ],
  });
}
